server:
  port: 5004

spring:
  application:
    name: pvp-service

data:
  service:
    url: ${DATA_SERVICE_URL:http://localhost:5003}

battle:
  service:
    url: ${BATTLE_SERVICE_URL:http://localhost:5001}
